//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentMex.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.PatientCard = new HashSet<PatientCard>();
            this.SavePatient2Visit = new HashSet<SavePatient2Visit>();
            this.TimeTable = new HashSet<TimeTable>();
            this.Visit = new HashSet<Visit>();
            this.Visit1 = new HashSet<Visit>();
        }
    
        public int AccountId { get; set; }
        public string AccountLogin { get; set; }
        public string Email { get; set; }
        public string AccountPassword { get; set; }
        public string InsuranceNumber { get; set; }
        public string Pesel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public short CityId { get; set; }
        public Nullable<short> GenderId { get; set; }
        public Nullable<short> UserRoleId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<PatientCard> PatientCard { get; set; }
        public virtual ICollection<SavePatient2Visit> SavePatient2Visit { get; set; }
        public virtual ICollection<TimeTable> TimeTable { get; set; }
        public virtual ICollection<Visit> Visit { get; set; }
        public virtual ICollection<Visit> Visit1 { get; set; }

        public string FullName { get { return FirstName + " " + LastName; }  }
    }
}
