//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentMex.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCard
    {
        public int PatientCardId { get; set; }
        public int PateintId { get; set; }
        public string Descryption { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
