//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentMex.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavePatient2Visit
    {
        public int SavePatient2VisitId { get; set; }
        public int PatientId { get; set; }
        public int VisitId { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
