//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentMex.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitState
    {
        public VisitState()
        {
            this.Visit = new HashSet<Visit>();
        }
    
        public int VisitStateId { get; set; }
        public string VisitStateName { get; set; }
    
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
