//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentMex.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.SavePatient2Visit = new HashSet<SavePatient2Visit>();
        }
    
        public int VisitId { get; set; }
        public int DentistId { get; set; }
        public Nullable<int> PateintId { get; set; }
        public int VisitStateId { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public Nullable<int> TimeOfVisit { get; set; }
        public string MakeServices { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> RecipeId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual ICollection<SavePatient2Visit> SavePatient2Visit { get; set; }
        public virtual VisitState VisitState { get; set; }
    }
}
